img.logo=logo.png
folderPdf=fc2526

#spring.datasource.url=jdbc:mysql://172.17.0.1:3306/fcapp?serverTimezone=Europe/Berlin
spring.datasource.url=jdbc:mysql://172.17.0.1:3306/fcapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=fcapp
spring.datasource.password=${fclt.db.password}

PATH_TMP=/app/data/
PATH_OUTPUT_PDF=/app/pdf/

#AUTUNNO-INVERNO
#ufficiosi.cron.expression=0 30 7 * * *
#ufficiali.cron.expression=0 30 15 * * *
#PRIMAVERA-ESTATE
#ufficiosi.cron.expression=0 30 6 * * *
#ufficiali.cron.expression=0 30 14 * * *
