package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.io.Serial;

/**
 * FcClassificaId generated by hbm2java
 */
@Embeddable
public class FcClassificaId implements java.io.Serializable{

	/**
	 *
	 */
	@Serial
    private static final long serialVersionUID = 1L;
	private int idAttore;
	private int idCampionato;

	public FcClassificaId() {
	}

	public FcClassificaId(int idAttore, int idCampionato) {
		this.idAttore = idAttore;
		this.idCampionato = idCampionato;
	}

	@Column(name = "id_attore", nullable = false)
	public int getIdAttore() {
		return this.idAttore;
	}

	public void setIdAttore(int idAttore) {
		this.idAttore = idAttore;
	}

	@Column(name = "id_campionato", nullable = false)
	public int getIdCampionato() {
		return this.idCampionato;
	}

	public void setIdCampionato(int idCampionato) {
		this.idCampionato = idCampionato;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if (!(other instanceof FcClassificaId castOther)) {
			return false;
		}

        return (this.getIdAttore() == castOther.getIdAttore()) && (this.getIdCampionato() == castOther.getIdCampionato());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttore();
		result = 37 * result + this.getIdCampionato();
		return result;
	}

}
