package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;
import java.sql.Blob;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * FcGiocatore generated by hbm2java
 */
@Entity
@Table(name = "fc_giocatore")
public class FcGiocatore implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id_giocatore", unique = true, nullable = false)
	private int idGiocatore;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ruolo")
	private FcRuolo fcRuolo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_squadra")
	private FcSquadra fcSquadra;

	@Column(name = "cogn_giocatore", nullable = false)
	private String cognGiocatore;

	@Column(name = "flag_attivo")
	private boolean flagAttivo;

	@Column(name = "nome_giocatore")
	private String nomeGiocatore;

	@Column(name = "nome_img")
	private String nomeImg;

	@Column(name = "quotazione")
	private Integer quotazione;

	@Column(name = "img")
	private Blob img;

	@Column(name = "img_small")
	private Blob imgSmall;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcGiocatore")
	private Set<FcPagelle> fcPagelles = new HashSet<>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcGiocatore")
	private Set<FcFormazione> fcFormaziones = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcGiocatore")
	private Set<FcGiornataDett> fcGiornataDetts = new HashSet<>(0);
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "fcGiocatore")
	private FcStatistiche fcStatistiche;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcGiocatoreByIdGiocVen")
	private Set<FcMercatoDett> fcMercatoDettsForIdGiocVen = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcGiocatoreByIdGiocAcq")
	private Set<FcMercatoDett> fcMercatoDettsForIdGiocAcq = new HashSet<>(0);

	@Column(name = "percentuale")
	private Integer percentuale;

	public FcGiocatore() {
	}

	public FcGiocatore(int idGiocatore, String cognGiocatore) {
		this.idGiocatore = idGiocatore;
		this.cognGiocatore = cognGiocatore;
	}

	public FcGiocatore(int idGiocatore, FcRuolo fcRuolo, FcSquadra fcSquadra,
			String cognGiocatore, boolean flagAttivo, String nomeGiocatore,
			String nomeImg, Integer quotazione, Set<FcPagelle> fcPagelles,
			Set<FcFormazione> fcFormaziones,
			Set<FcGiornataDett> fcGiornataDetts, FcStatistiche fcStatistiche,
			Set<FcMercatoDett> fcMercatoDettsForIdGiocVen,
			Set<FcMercatoDett> fcMercatoDettsForIdGiocAcq) {
		this.idGiocatore = idGiocatore;
		this.fcRuolo = fcRuolo;
		this.fcSquadra = fcSquadra;
		this.cognGiocatore = cognGiocatore;
		this.flagAttivo = flagAttivo;
		this.nomeGiocatore = nomeGiocatore;
		this.nomeImg = nomeImg;
		this.quotazione = quotazione;
		this.fcPagelles = fcPagelles;
		this.fcFormaziones = fcFormaziones;
		this.fcGiornataDetts = fcGiornataDetts;
		this.fcStatistiche = fcStatistiche;
		this.fcMercatoDettsForIdGiocVen = fcMercatoDettsForIdGiocVen;
		this.fcMercatoDettsForIdGiocAcq = fcMercatoDettsForIdGiocAcq;
	}

	public int getIdGiocatore() {
		return this.idGiocatore;
	}

	public void setIdGiocatore(int idGiocatore) {
		this.idGiocatore = idGiocatore;
	}

	public FcRuolo getFcRuolo() {
		return this.fcRuolo;
	}

	public void setFcRuolo(FcRuolo fcRuolo) {
		this.fcRuolo = fcRuolo;
	}

	public FcSquadra getFcSquadra() {
		return this.fcSquadra;
	}

	public void setFcSquadra(FcSquadra fcSquadra) {
		this.fcSquadra = fcSquadra;
	}

	public String getCognGiocatore() {
		return this.cognGiocatore;
	}

	public void setCognGiocatore(String cognGiocatore) {
		this.cognGiocatore = cognGiocatore;
	}

	public boolean isFlagAttivo() {
		return this.flagAttivo;
	}

	public void setFlagAttivo(boolean flagAttivo) {
		this.flagAttivo = flagAttivo;
	}

	public String getNomeGiocatore() {
		return this.nomeGiocatore;
	}

	public void setNomeGiocatore(String nomeGiocatore) {
		this.nomeGiocatore = nomeGiocatore;
	}

	public String getNomeImg() {
		return this.nomeImg;
	}

	public void setNomeImg(String nomeImg) {
		this.nomeImg = nomeImg;
	}

	public Integer getQuotazione() {
		return this.quotazione;
	}

	public void setQuotazione(Integer quotazione) {
		this.quotazione = quotazione;
	}

	public Blob getImg() {
		return this.img;
	}

	public void setImg(Blob img) {
		this.img = img;
	}

	public Blob getImgSmall() {
		return this.imgSmall;
	}

	public void setImgSmall(Blob imgSmall) {
		this.imgSmall = imgSmall;
	}

	public Set<FcPagelle> getFcPagelles() {
		return this.fcPagelles;
	}

	public void setFcPagelles(Set<FcPagelle> fcPagelles) {
		this.fcPagelles = fcPagelles;
	}

	public Set<FcFormazione> getFcFormaziones() {
		return this.fcFormaziones;
	}

	public void setFcFormaziones(Set<FcFormazione> fcFormaziones) {
		this.fcFormaziones = fcFormaziones;
	}

	public Set<FcGiornataDett> getFcGiornataDetts() {
		return this.fcGiornataDetts;
	}

	public void setFcGiornataDetts(Set<FcGiornataDett> fcGiornataDetts) {
		this.fcGiornataDetts = fcGiornataDetts;
	}

	public FcStatistiche getFcStatistiche() {
		return this.fcStatistiche;
	}

	public void setFcStatistiche(FcStatistiche fcStatistiche) {
		this.fcStatistiche = fcStatistiche;
	}

	public Set<FcMercatoDett> getFcMercatoDettsForIdGiocVen() {
		return this.fcMercatoDettsForIdGiocVen;
	}

	public void setFcMercatoDettsForIdGiocVen(
			Set<FcMercatoDett> fcMercatoDettsForIdGiocVen) {
		this.fcMercatoDettsForIdGiocVen = fcMercatoDettsForIdGiocVen;
	}

	public Set<FcMercatoDett> getFcMercatoDettsForIdGiocAcq() {
		return this.fcMercatoDettsForIdGiocAcq;
	}

	public void setFcMercatoDettsForIdGiocAcq(
			Set<FcMercatoDett> fcMercatoDettsForIdGiocAcq) {
		this.fcMercatoDettsForIdGiocAcq = fcMercatoDettsForIdGiocAcq;
	}

	@Column(name = "data", nullable = false)
	private LocalDateTime data;

	public LocalDateTime getData() {
		return data;
	}

	public void setData(LocalDateTime data) {
		this.data = data;
	}

	public Integer getPercentuale() {
		return percentuale;
	}

	public void setPercentuale(Integer percentuale) {
		this.percentuale = percentuale;
	}

}
