package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.io.Serial;

/**
 * FcGiornataId generated by hbm2java
 */
@Embeddable
public class FcGiornataId implements java.io.Serializable{

	/**
	 *
	 */
	@Serial
    private static final long serialVersionUID = 1L;
	private int idAttoreCasa;
	private int idGiornata;

	public FcGiornataId() {
	}

	public FcGiornataId(int idAttoreCasa, int idGiornata) {
		this.idAttoreCasa = idAttoreCasa;
		this.idGiornata = idGiornata;
	}

	@Column(name = "id_attore_casa", nullable = false)
	public int getIdAttoreCasa() {
		return this.idAttoreCasa;
	}

	public void setIdAttoreCasa(int idAttoreCasa) {
		this.idAttoreCasa = idAttoreCasa;
	}

	@Column(name = "id_giornata", nullable = false)
	public int getIdGiornata() {
		return this.idGiornata;
	}

	public void setIdGiornata(int idGiornata) {
		this.idGiornata = idGiornata;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if (!(other instanceof FcGiornataId castOther)) {
			return false;
		}

        return (this.getIdAttoreCasa() == castOther.getIdAttoreCasa()) && (this.getIdGiornata() == castOther.getIdGiornata());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttoreCasa();
		result = 37 * result + this.getIdGiornata();
		return result;
	}

}
