package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;
import java.util.Date;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * FcGiornataDettInfo generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_dett_info")
public class FcGiornataDettInfo implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	private FcGiornataDettInfoId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	private FcAttore fcAttore;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	private FcGiornataInfo fcGiornataInfo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_invio", nullable = false, length = 19)
	private Date dataInvio;

	@Column(name = "flag_invio", nullable = false)
	private boolean flagInvio;

	public FcGiornataDettInfo() {
	}

	public FcGiornataDettInfo(FcGiornataDettInfoId id, FcAttore fcAttore,
			FcGiornataInfo fcGiornataInfo, Date dataInvio, boolean flagInvio) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.dataInvio = dataInvio;
		this.flagInvio = flagInvio;
	}

	public FcGiornataDettInfoId getId() {
		return this.id;
	}

	public void setId(FcGiornataDettInfoId id) {
		this.id = id;
	}

	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	public Date getDataInvio() {
		return this.dataInvio;
	}

	public void setDataInvio(Date dataInvio) {
		this.dataInvio = dataInvio;
	}

	public boolean getFlagInvio() {
		return this.flagInvio;
	}

	public void setFlagInvio(boolean flagInvio) {
		this.flagInvio = flagInvio;
	}

}
