package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.io.Serial;

/**
 * FcGiornataDettInfoId generated by hbm2java
 */
@Embeddable
public class FcGiornataDettInfoId implements java.io.Serializable{

	/**
	 *
	 */
	@Serial
    private static final long serialVersionUID = 1L;
	private int idAttore;
	private int idGiornata;

	public FcGiornataDettInfoId() {
	}

	public FcGiornataDettInfoId(int idAttore, int idGiornata) {
		this.idAttore = idAttore;
		this.idGiornata = idGiornata;
	}

	@Column(name = "id_attore", nullable = false)
	public int getIdAttore() {
		return this.idAttore;
	}

	public void setIdAttore(int idAttore) {
		this.idAttore = idAttore;
	}

	@Column(name = "id_giornata", nullable = false)
	public int getIdGiornata() {
		return this.idGiornata;
	}

	public void setIdGiornata(int idGiornata) {
		this.idGiornata = idGiornata;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if (!(other instanceof FcGiornataDettInfoId castOther)) {
			return false;
		}

        return (this.getIdAttore() == castOther.getIdAttore()) && (this.getIdGiornata() == castOther.getIdGiornata());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttore();
		result = 37 * result + this.getIdGiornata();
		return result;
	}

}
