package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serial;

/**
 * FcProperties generated by hbm2java
 */
@Entity
@Table(name = "fc_properties")
public class FcProperties implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "key_", unique = true, nullable = false)
	private String key;

	@Column(name = "value_", nullable = false)
	private String value;

	public FcProperties() {
	}

	public FcProperties(String key, String value) {
		this.key = key;
		this.value = value;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
