package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * FcSquadra generated by hbm2java
 */
@Entity
@Table(name = "fc_squadra")
public class FcSquadra implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id_squadra", unique = true, nullable = false)
	private int idSquadra;

	@Column(name = "nome_squadra", nullable = false)
	private String nomeSquadra;
	
	@Column(name = "nome_img")
	private String nomeImg;

	@Column(name = "img")
	private Blob img;

	@Column(name = "img40")
	private Blob img40;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcSquadra")
	private Set<FcGiocatore> fcGiocatores = new HashSet<>(0);

	public FcSquadra() {
	}

	public FcSquadra(int idSquadra, String nomeSquadra) {
		this.idSquadra = idSquadra;
		this.nomeSquadra = nomeSquadra;
	}

	public FcSquadra(int idSquadra, String nomeSquadra,
			Set<FcGiocatore> fcGiocatores) {
		this.idSquadra = idSquadra;
		this.nomeSquadra = nomeSquadra;
		this.fcGiocatores = fcGiocatores;
	}

	public int getIdSquadra() {
		return this.idSquadra;
	}

	public void setIdSquadra(int idSquadra) {
		this.idSquadra = idSquadra;
	}

	public String getNomeSquadra() {
		return this.nomeSquadra;
	}

	public void setNomeSquadra(String nomeSquadra) {
		this.nomeSquadra = nomeSquadra;
	}

	public Set<FcGiocatore> getFcGiocatores() {
		return this.fcGiocatores;
	}

	public void setFcGiocatores(Set<FcGiocatore> fcGiocatores) {
		this.fcGiocatores = fcGiocatores;
	}

	public String getNomeImg() {
		return this.nomeImg;
	}

	public void setNomeImg(String nomeImg) {
		this.nomeImg = nomeImg;
	}

	public Blob getImg() {
		return this.img;
	}

	public void setImg(Blob img) {
		this.img = img;
	}

	public Blob getImg40() {
		return this.img40;
	}

	public void setImg40(Blob img40) {
		this.img40 = img40;
	}

}
