package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;

import java.io.Serial;

/**
 * FcStatistiche generated by hbm2java
 */
@Entity
@Table(name = "fc_statistiche")
public class FcStatistiche implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	// @GeneratedValue(generator = "generator")
	@SuppressWarnings("deprecation")
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "fcGiocatore"))
	@Id
	@Column(name = "id_giocatore", unique = true, nullable = false)
	private int idGiocatore;

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private FcGiocatore fcGiocatore;

	@Column(name = "ammonizione", nullable = false)
	private int ammonizione;

	@Column(name = "assist", nullable = false)
	private int assist;

	@Column(name = "cogn_giocatore", nullable = false)
	private String cognGiocatore;

	@Column(name = "espulsione", nullable = false)
	private int espulsione;

	@Column(name = "fanta_media", precision = 22, scale = 0)
	private Double fantaMedia;

	@Column(name = "giocate", nullable = false)
	private int giocate;

	@Column(name = "goal_fatto", nullable = false)
	private int goalFatto;

	@Column(name = "goal_subito", nullable = false)
	private int goalSubito;

	@Column(name = "id_ruolo", nullable = false)
	private String idRuolo;

	@Column(name = "media_voto", precision = 22, scale = 0)
	private Double mediaVoto;
	
	@Column(name = "nome_squadra", nullable = false)
	private String nomeSquadra;

	@Column(name = "proprietario")
	private String proprietario;

	@Column(name = "rigore_sbagliato", nullable = false)
	private int rigoreSbagliato;

	@Column(name = "rigore_segnato", nullable = false)
	private int rigoreSegnato;

	@Column(name = "flag_attivo", columnDefinition = "boolean default true")
	private boolean flagAttivo;

	public FcStatistiche() {
	}

	public FcStatistiche(FcGiocatore fcGiocatore, int ammonizione, int assist,
			String cognGiocatore, int espulsione, int giocate, int goalFatto,
			int goalSubito, String idRuolo, String nomeSquadra,
			int rigoreSbagliato, int rigoreSegnato) {
		this.fcGiocatore = fcGiocatore;
		this.ammonizione = ammonizione;
		this.assist = assist;
		this.cognGiocatore = cognGiocatore;
		this.espulsione = espulsione;
		this.giocate = giocate;
		this.goalFatto = goalFatto;
		this.goalSubito = goalSubito;
		this.idRuolo = idRuolo;
		this.nomeSquadra = nomeSquadra;
		this.rigoreSbagliato = rigoreSbagliato;
		this.rigoreSegnato = rigoreSegnato;
	}

	public FcStatistiche(FcGiocatore fcGiocatore, int ammonizione, int assist,
			String cognGiocatore, int espulsione, Double fantaMedia,
			int giocate, int goalFatto, int goalSubito, String idRuolo,
			Double mediaVoto, String nomeSquadra, String proprietario,
			int rigoreSbagliato, int rigoreSegnato) {
		this.fcGiocatore = fcGiocatore;
		this.ammonizione = ammonizione;
		this.assist = assist;
		this.cognGiocatore = cognGiocatore;
		this.espulsione = espulsione;
		this.fantaMedia = fantaMedia;
		this.giocate = giocate;
		this.goalFatto = goalFatto;
		this.goalSubito = goalSubito;
		this.idRuolo = idRuolo;
		this.mediaVoto = mediaVoto;
		this.nomeSquadra = nomeSquadra;
		this.proprietario = proprietario;
		this.rigoreSbagliato = rigoreSbagliato;
		this.rigoreSegnato = rigoreSegnato;
	}

	public int getIdGiocatore() {
		return this.idGiocatore;
	}

	public void setIdGiocatore(int idGiocatore) {
		this.idGiocatore = idGiocatore;
	}

	public FcGiocatore getFcGiocatore() {
		return this.fcGiocatore;
	}

	public void setFcGiocatore(FcGiocatore fcGiocatore) {
		this.fcGiocatore = fcGiocatore;
	}

	public int getAmmonizione() {
		return this.ammonizione;
	}

	public void setAmmonizione(int ammonizione) {
		this.ammonizione = ammonizione;
	}

	public int getAssist() {
		return this.assist;
	}

	public void setAssist(int assist) {
		this.assist = assist;
	}

	public String getCognGiocatore() {
		return this.cognGiocatore;
	}

	public void setCognGiocatore(String cognGiocatore) {
		this.cognGiocatore = cognGiocatore;
	}

	public int getEspulsione() {
		return this.espulsione;
	}

	public void setEspulsione(int espulsione) {
		this.espulsione = espulsione;
	}

	public Double getFantaMedia() {
		return this.fantaMedia;
	}

	public void setFantaMedia(Double fantaMedia) {
		this.fantaMedia = fantaMedia;
	}

	public int getGiocate() {
		return this.giocate;
	}

	public void setGiocate(int giocate) {
		this.giocate = giocate;
	}

	public int getGoalFatto() {
		return this.goalFatto;
	}

	public void setGoalFatto(int goalFatto) {
		this.goalFatto = goalFatto;
	}

	public int getGoalSubito() {
		return this.goalSubito;
	}

	public void setGoalSubito(int goalSubito) {
		this.goalSubito = goalSubito;
	}

	public String getIdRuolo() {
		return this.idRuolo;
	}

	public void setIdRuolo(String idRuolo) {
		this.idRuolo = idRuolo;
	}

	public Double getMediaVoto() {
		return this.mediaVoto;
	}

	public void setMediaVoto(Double mediaVoto) {
		this.mediaVoto = mediaVoto;
	}

	public String getNomeSquadra() {
		return this.nomeSquadra;
	}

	public void setNomeSquadra(String nomeSquadra) {
		this.nomeSquadra = nomeSquadra;
	}

	public String getProprietario() {
		return this.proprietario;
	}

	public void setProprietario(String proprietario) {
		this.proprietario = proprietario;
	}

	public int getRigoreSbagliato() {
		return this.rigoreSbagliato;
	}

	public void setRigoreSbagliato(int rigoreSbagliato) {
		this.rigoreSbagliato = rigoreSbagliato;
	}

	public int getRigoreSegnato() {
		return this.rigoreSegnato;
	}

	public void setRigoreSegnato(int rigoreSegnato) {
		this.rigoreSegnato = rigoreSegnato;
	}

	public boolean isFlagAttivo() {
		return this.flagAttivo;
	}

	public void setFlagAttivo(boolean flagAttivo) {
		this.flagAttivo = flagAttivo;
	}

}
