package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * FcTipoGiornata generated by hbm2java
 */
@Entity
@Table(name = "fc_tipo_giornata")
public class FcTipoGiornata implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private int idTipoGiornata;
    private String descTipoGiornata;
    private Set<FcGiornata> fcGiornatas = new HashSet<>(0);

    public FcTipoGiornata() {
    }

    public FcTipoGiornata(int idTipoGiornata, String descTipoGiornata) {
        this.idTipoGiornata = idTipoGiornata;
        this.descTipoGiornata = descTipoGiornata;
    }

    public FcTipoGiornata(int idTipoGiornata, String descTipoGiornata, Set<FcGiornata> fcGiornatas) {
        this.idTipoGiornata = idTipoGiornata;
        this.descTipoGiornata = descTipoGiornata;
        this.fcGiornatas = fcGiornatas;
    }

    @Id

    @Column(name = "id_tipo_giornata", unique = true, nullable = false)
    public int getIdTipoGiornata() {
        return this.idTipoGiornata;
    }

    public void setIdTipoGiornata(int idTipoGiornata) {
        this.idTipoGiornata = idTipoGiornata;
    }

    @Column(name = "desc_tipo_giornata", nullable = false)
    public String getDescTipoGiornata() {
        return this.descTipoGiornata;
    }

    public void setDescTipoGiornata(String descTipoGiornata) {
        this.descTipoGiornata = descTipoGiornata;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fcTipoGiornata")
    public Set<FcGiornata> getFcGiornatas() {
        return this.fcGiornatas;
    }

    public void setFcGiornatas(Set<FcGiornata> fcGiornatas) {
        this.fcGiornatas = fcGiornatas;
    }

}
