package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * FcClassificaTotPt generated by hbm2java
 */
@Entity
@Table(name = "fc_classifica_tot_pt")
public class FcClassificaTotPt implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idCampionato", column = @Column(name = "id_campionato", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	private FcClassificaTotPtId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	private FcAttore fcAttore;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_campionato", nullable = false, insertable = false, updatable = false)
	private FcCampionato fcCampionato;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	private FcGiornataInfo fcGiornataInfo;

	@Column(name = "score", nullable = false, columnDefinition = "int default 0")
	private int score;

	@Column(name = "score_grand_prix", nullable = false, columnDefinition = "int default 0")
	private int scoreGrandPrix;

	@Column(name = "score_old", nullable = false, columnDefinition = "int default 0")
	private int scoreOld;

	@Column(name = "tot_pt", precision = 22, scale = 0)
	private Double totPt;

	@Column(name = "tot_pt_old", precision = 22, scale = 0)
	private Double totPtOld;

	@Column(name = "tot_pt_rosa", precision = 22, scale = 0)
	private Double totPtRosa;

	@Column(name = "goal", nullable = false, columnDefinition = "int default 0")
	private int goal;

	@Column(name = "ptTvsT", nullable = false, columnDefinition = "int default 0")
	private int ptTvsT;

	public FcClassificaTotPt() {
	}

	public FcClassificaTotPt(FcClassificaTotPtId id, FcAttore fcAttore,
			FcCampionato fcCampionato, FcGiornataInfo fcGiornataInfo, int score,
			int scoreGrandPrix, int scoreOld) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcCampionato = fcCampionato;
		this.fcGiornataInfo = fcGiornataInfo;
		this.score = score;
		this.scoreGrandPrix = scoreGrandPrix;
		this.scoreOld = scoreOld;
	}

	public FcClassificaTotPt(FcClassificaTotPtId id, FcAttore fcAttore,
			FcCampionato fcCampionato, FcGiornataInfo fcGiornataInfo, int score,
			int scoreGrandPrix, int scoreOld, Double totPt, Double totPtOld,
			Double totPtRosa) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcCampionato = fcCampionato;
		this.fcGiornataInfo = fcGiornataInfo;
		this.score = score;
		this.scoreGrandPrix = scoreGrandPrix;
		this.scoreOld = scoreOld;
		this.totPt = totPt;
		this.totPtOld = totPtOld;
		this.totPtRosa = totPtRosa;
	}

	public FcClassificaTotPtId getId() {
		return this.id;
	}

	public void setId(FcClassificaTotPtId id) {
		this.id = id;
	}

	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	public FcCampionato getFcCampionato() {
		return this.fcCampionato;
	}

	public void setFcCampionato(FcCampionato fcCampionato) {
		this.fcCampionato = fcCampionato;
	}

	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public int getScoreGrandPrix() {
		return this.scoreGrandPrix;
	}

	public void setScoreGrandPrix(int scoreGrandPrix) {
		this.scoreGrandPrix = scoreGrandPrix;
	}

	public int getScoreOld() {
		return this.scoreOld;
	}

	public void setScoreOld(int scoreOld) {
		this.scoreOld = scoreOld;
	}

	public Double getTotPt() {
		return this.totPt;
	}

	public void setTotPt(Double totPt) {
		this.totPt = totPt;
	}

	public Double getTotPtOld() {
		return this.totPtOld;
	}

	public void setTotPtOld(Double totPtOld) {
		this.totPtOld = totPtOld;
	}

	public Double getTotPtRosa() {
		return this.totPtRosa;
	}

	public void setTotPtRosa(Double totPtRosa) {
		this.totPtRosa = totPtRosa;
	}

	public int getGoal() {
		return this.goal;
	}

	public void setGoal(int goal) {
		this.goal = goal;
	}

	public int getPtTvsT() {
		return ptTvsT;
	}

	public void setPtTvsT(int ptTvsT) {
		this.ptTvsT = ptTvsT;
	}

}
