package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serial;

/**
 * FcExpStat generated by hbm2java
 */
@Entity
@Table(name = "fc_exp_stat")
public class FcExpStat implements java.io.Serializable{

	/**
	 *
	 */
	@Serial
    private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "anno")
	private String anno;
	
	@Column(name = "campionato")
	private String campionato;
	
	@Column(name = "p2")
	private String p2;
	
	@Column(name = "p3")
	private String p3;
	
	@Column(name = "p4")
	private String p4;
	
	@Column(name = "p5")
	private String p5;
	
	@Column(name = "p6")
	private String p6;
	
	@Column(name = "p7")
	private String p7;
	
	@Column(name = "p8")
	private String p8;

	@Column(name = "scudetto")
	private String scudetto;

	@Column(name = "win_clas_pt")
	private String winClasPt;

	@Column(name = "win_clas_reg")
	private String winClasReg;

	@Column(name = "win_clas_TvsT")
	private String winClasTvsT;

	public FcExpStat() {
	}

	public FcExpStat(int id) {
		this.id = id;
	}

	public FcExpStat(int id, String anno, String campionato, String p2,
			String p3, String p4, String p5, String p6, String p7, String p8,
			String scudetto, String winClasPt, String winClasReg,
			String winClasTvsT) {
		this.id = id;
		this.anno = anno;
		this.campionato = campionato;
		this.p2 = p2;
		this.p3 = p3;
		this.p4 = p4;
		this.p5 = p5;
		this.p6 = p6;
		this.p7 = p7;
		this.p8 = p8;
		this.scudetto = scudetto;
		this.winClasPt = winClasPt;
		this.winClasReg = winClasReg;
		this.winClasTvsT = winClasTvsT;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAnno() {
		return this.anno;
	}

	public void setAnno(String anno) {
		this.anno = anno;
	}

	public String getCampionato() {
		return this.campionato;
	}

	public void setCampionato(String campionato) {
		this.campionato = campionato;
	}

	public String getP2() {
		return this.p2;
	}

	public void setP2(String p2) {
		this.p2 = p2;
	}

	public String getP3() {
		return this.p3;
	}

	public void setP3(String p3) {
		this.p3 = p3;
	}

	public String getP4() {
		return this.p4;
	}

	public void setP4(String p4) {
		this.p4 = p4;
	}

	public String getP5() {
		return this.p5;
	}

	public void setP5(String p5) {
		this.p5 = p5;
	}

	public String getP6() {
		return this.p6;
	}

	public void setP6(String p6) {
		this.p6 = p6;
	}

	public String getP7() {
		return this.p7;
	}

	public void setP7(String p7) {
		this.p7 = p7;
	}

	public String getP8() {
		return this.p8;
	}

	public void setP8(String p8) {
		this.p8 = p8;
	}

	public String getScudetto() {
		return this.scudetto;
	}

	public void setScudetto(String scudetto) {
		this.scudetto = scudetto;
	}

	public String getWinClasPt() {
		return this.winClasPt;
	}

	public void setWinClasPt(String winClasPt) {
		this.winClasPt = winClasPt;
	}

	public String getWinClasReg() {
		return this.winClasReg;
	}

	public void setWinClasReg(String winClasReg) {
		this.winClasReg = winClasReg;
	}

	public String getWinClasTvsT() {
		return this.winClasTvsT;
	}

	public void setWinClasTvsT(String winClasTvsT) {
		this.winClasTvsT = winClasTvsT;
	}

}
