package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * FcFormazioneId generated by hbm2java
 */
@Embeddable
public class FcFormazioneId implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;

	@Column(name = "id_attore", nullable = false)
	private int idAttore;

	@Column(name = "id_campionato", nullable = false)
	private int idCampionato;

	@Column(name = "ordinamento", nullable = false)
	private int ordinamento;

	public FcFormazioneId() {
	}

	public FcFormazioneId(int idAttore, int idCampionato, int ordinamento) {
		this.idAttore = idAttore;
		this.idCampionato = idCampionato;
		this.ordinamento = ordinamento;
	}

	public int getIdAttore() {
		return this.idAttore;
	}

	public void setIdAttore(int idAttore) {
		this.idAttore = idAttore;
	}

	public int getIdCampionato() {
		return this.idCampionato;
	}

	public void setIdCampionato(int idCampionato) {
		this.idCampionato = idCampionato;
	}

	public int getOrdinamento() {
		return this.ordinamento;
	}

	public void setOrdinamento(int ordinamento) {
		this.ordinamento = ordinamento;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if (!(other instanceof FcFormazioneId castOther)) {
			return false;
		}

        return (this.getIdAttore() == castOther.getIdAttore()) && (this.getIdCampionato() == castOther.getIdCampionato()) && (this.getOrdinamento() == castOther.getOrdinamento());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttore();
		result = 37 * result + this.getIdCampionato();
		result = 37 * result + this.getOrdinamento();
		return result;
	}

}
