package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.io.Serial;

/**
 * FcGiornataRis generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_ris")
public class FcGiornataRis implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	private FcGiornataRisId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	private FcAttore fcAttore;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	private FcGiornataInfo fcGiornataInfo;

	@Column(name = "fm")
	private Integer fm;

	@Column(name = "gf")
	private Integer gf;

	@Column(name = "gs")
	private Integer gs;

	@Column(name = "id_ris_partita", nullable = false)
	private int idRisPartita;

	@Column(name = "nulla")
	private Integer nulla;

	@Column(name = "persa")
	private Integer persa;

	@Column(name = "punti")
	private Integer punti;

	@Column(name = "vinta")
	private Integer vinta;

	@Column(name = "casafuori")
	private Integer casafuori;

	public FcGiornataRis() {
	}

	public FcGiornataRis(FcGiornataRisId id, FcAttore fcAttore,
			FcGiornataInfo fcGiornataInfo, int idRisPartita) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.idRisPartita = idRisPartita;
	}

	public FcGiornataRis(FcGiornataRisId id, FcAttore fcAttore,
			FcGiornataInfo fcGiornataInfo, Integer fm, Integer gf, Integer gs,
			int idRisPartita, Integer nulla, Integer persa, Integer punti,
			Integer vinta) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.fm = fm;
		this.gf = gf;
		this.gs = gs;
		this.idRisPartita = idRisPartita;
		this.nulla = nulla;
		this.persa = persa;
		this.punti = punti;
		this.vinta = vinta;
	}

	public FcGiornataRisId getId() {
		return this.id;
	}

	public void setId(FcGiornataRisId id) {
		this.id = id;
	}

	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	public Integer getFm() {
		return this.fm;
	}

	public void setFm(Integer fm) {
		this.fm = fm;
	}

	public Integer getGf() {
		return this.gf;
	}

	public void setGf(Integer gf) {
		this.gf = gf;
	}

	public Integer getGs() {
		return this.gs;
	}

	public void setGs(Integer gs) {
		this.gs = gs;
	}

	public int getIdRisPartita() {
		return this.idRisPartita;
	}

	public void setIdRisPartita(int idRisPartita) {
		this.idRisPartita = idRisPartita;
	}

	public Integer getNulla() {
		return this.nulla;
	}

	public void setNulla(Integer nulla) {
		this.nulla = nulla;
	}

	public Integer getPersa() {
		return this.persa;
	}

	public void setPersa(Integer persa) {
		this.persa = persa;
	}

	public Integer getPunti() {
		return this.punti;
	}

	public void setPunti(Integer punti) {
		this.punti = punti;
	}

	public Integer getVinta() {
		return this.vinta;
	}

	public void setVinta(Integer vinta) {
		this.vinta = vinta;
	}

	public Integer getCasaFuori() {
		return this.casafuori;
	}

	public void setCasaFuori(Integer casafuori) {
		this.casafuori = casafuori;
	}

}
