package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * FcPagelle generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_giocatore")
public class FcGiornataGiocatore implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	private FcGiornataGiocatoreId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	private FcGiocatore fcGiocatore;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	private FcGiornataInfo fcGiornataInfo;

	@Column(name = "infortunato")
	private boolean infortunato;
	
	@Column(name = "squalificato")
	private boolean squalificato;

	@Column(name = "note", nullable = true)
	private String note;

	public FcGiornataGiocatore() {
	}

	public FcGiornataGiocatoreId getId() {
		return this.id;
	}

	public void setId(FcGiornataGiocatoreId id) {
		this.id = id;
	}

	public FcGiocatore getFcGiocatore() {
		return this.fcGiocatore;
	}

	public void setFcGiocatore(FcGiocatore fcGiocatore) {
		this.fcGiocatore = fcGiocatore;
	}

	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	public boolean isInfortunato() {
		return this.infortunato;
	}

	public void setInfortunato(boolean infortunato) {
		this.infortunato = infortunato;
	}

	public boolean isSqualificato() {
		return this.squalificato;
	}

	public void setSqualificato(boolean squalificato) {
		this.squalificato = squalificato;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
