package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinColumns;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * FcGiornataDett generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_dett")
public class FcGiornataDett implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	private FcGiornataDettId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	private FcAttore fcAttore;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	private FcGiocatore fcGiocatore;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	private FcGiornataInfo fcGiornataInfo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "id_giocatore", referencedColumnName = "id_giocatore", nullable = false, insertable = false, updatable = false), @JoinColumn(name = "id_giornata", referencedColumnName = "id_giornata", nullable = false, insertable = false, updatable = false) })
	private FcPagelle fcPagelle;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_stato_giocatore")
	private FcStatoGiocatore fcStatoGiocatore;

	@Column(name = "flag_attivo")
	private String flagAttivo;
	
	@Column(name = "ordinamento", nullable = false)
	private int ordinamento;

	@Column(name = "voto", precision = 22, scale = 0)
	private Double voto;

	public FcGiornataDett() {
	}

	public FcGiornataDett(FcGiornataDettId id, FcAttore fcAttore,
			FcGiocatore fcGiocatore, FcGiornataInfo fcGiornataInfo,
			FcPagelle fcPagelle, int ordinamento) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiocatore = fcGiocatore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.fcPagelle = fcPagelle;
		this.ordinamento = ordinamento;
	}

	public FcGiornataDett(FcGiornataDettId id, FcAttore fcAttore,
			FcGiocatore fcGiocatore, FcGiornataInfo fcGiornataInfo,
			FcPagelle fcPagelle, FcStatoGiocatore fcStatoGiocatore,
			String flagAttivo, int ordinamento, Double voto) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiocatore = fcGiocatore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.fcPagelle = fcPagelle;
		this.fcStatoGiocatore = fcStatoGiocatore;
		this.flagAttivo = flagAttivo;
		this.ordinamento = ordinamento;
		this.voto = voto;
	}

	public FcGiornataDettId getId() {
		return this.id;
	}

	public void setId(FcGiornataDettId id) {
		this.id = id;
	}

	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	public FcGiocatore getFcGiocatore() {
		return this.fcGiocatore;
	}

	public void setFcGiocatore(FcGiocatore fcGiocatore) {
		this.fcGiocatore = fcGiocatore;
	}

	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	public FcPagelle getFcPagelle() {
		return this.fcPagelle;
	}

	public void setFcPagelle(FcPagelle fcPagelle) {
		this.fcPagelle = fcPagelle;
	}

	public FcStatoGiocatore getFcStatoGiocatore() {
		return this.fcStatoGiocatore;
	}

	public void setFcStatoGiocatore(FcStatoGiocatore fcStatoGiocatore) {
		this.fcStatoGiocatore = fcStatoGiocatore;
	}

	public String getFlagAttivo() {
		return this.flagAttivo;
	}

	public void setFlagAttivo(String flagAttivo) {
		this.flagAttivo = flagAttivo;
	}

	public int getOrdinamento() {
		return this.ordinamento;
	}

	public void setOrdinamento(int ordinamento) {
		this.ordinamento = ordinamento;
	}

	public Double getVoto() {
		return this.voto;
	}

	public void setVoto(Double voto) {
		this.voto = voto;
	}

}
