package fcapp.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.io.Serial;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * FcTipoGiornata generated by hbm2java
 */
@Entity
@Table(name = "fc_tipo_giornata")
public class FcTipoGiornata implements java.io.Serializable{

	@Serial
    private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id_tipo_giornata", unique = true, nullable = false)
	private int idTipoGiornata;

	@Column(name = "desc_tipo_giornata", nullable = false)
	private String descTipoGiornata;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcTipoGiornata")
	private Set<FcGiornata> fcGiornatas = new HashSet<>(0);

	public FcTipoGiornata() {
	}

	public FcTipoGiornata(int idTipoGiornata, String descTipoGiornata) {
		this.idTipoGiornata = idTipoGiornata;
		this.descTipoGiornata = descTipoGiornata;
	}

	public FcTipoGiornata(int idTipoGiornata, String descTipoGiornata,
			Set<FcGiornata> fcGiornatas) {
		this.idTipoGiornata = idTipoGiornata;
		this.descTipoGiornata = descTipoGiornata;
		this.fcGiornatas = fcGiornatas;
	}

	public int getIdTipoGiornata() {
		return this.idTipoGiornata;
	}

	public void setIdTipoGiornata(int idTipoGiornata) {
		this.idTipoGiornata = idTipoGiornata;
	}

	public String getDescTipoGiornata() {
		return this.descTipoGiornata;
	}

	public void setDescTipoGiornata(String descTipoGiornata) {
		this.descTipoGiornata = descTipoGiornata;
	}

	public Set<FcGiornata> getFcGiornatas() {
		return this.fcGiornatas;
	}

	public void setFcGiornatas(Set<FcGiornata> fcGiornatas) {
		this.fcGiornatas = fcGiornatas;
	}

}
